{
    "openapi": "3.0.2",
    "info": {
        "title": "identity-verificate-service",
        "version": "1.0",
        "description": "本人性確認サービス"
    },
    "servers": [
        {
            "url": "/identity-verificate"
        }
    ],
    "paths": {
        "/code": {
            "post": {
                "tags": [
                    "本人性確認コード発行"
                ],
                "description": "本人性確認コードを発行し、WF関連の発行処理の場合はWFメンバーへの通知も行います。",
                "requestBody": {
                    "description": "本人性確認コード発行用のリクエスト",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "description": "発行情報",
                                "properties": {
                                    "actor": {
                                        "type": "object",
                                        "properties": {
                                            "_value": {
                                                "type": "integer",
                                                "description": "カタログコード"
                                            },
                                            "_ver": {
                                                "type": "integer",
                                                "description": "カタログバージョン"
                                            }
                                        },
                                        "description": "アクターカタログコードオブジェクト"
                                    },
                                    "wf": {
                                        "type": "object",
                                        "properties": {
                                            "_value": {
                                                "type": "integer",
                                                "description": "カタログコード"
                                            },
                                            "_ver": {
                                                "type": "integer",
                                                "description": "カタログバージョン"
                                            }
                                        },
                                        "description": "WF定義カタログコードオブジェクト"
                                    },
                                    "app": {
                                        "type": "object",
                                        "properties": {
                                            "_value": {
                                                "type": "integer",
                                                "description": "カタログコード"
                                            },
                                            "_ver": {
                                                "type": "integer",
                                                "description": "カタログバージョン"
                                            }
                                        },
                                        "description": "APP定義カタログコードオブジェクト"
                                    }
                                },
                                "example": {
                                    "actor": {
                                        "_value": 1000004,
                                        "_ver": 1
                                    },
                                    "app": null,
                                    "wf": {
                                        "_value": 1000007,
                                        "_ver": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "コード発行に成功した際のレスポンス",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "description": "発行情報",
                                    "properties": {
                                        "identifyCode": {
                                            "type": "string",
                                            "description": "本人性確認コード"
                                        },
                                        "actor": {
                                            "type": "object",
                                            "properties": {
                                                "_value": {
                                                    "type": "integer",
                                                    "description": "カタログコード"
                                                },
                                                "_ver": {
                                                    "type": "integer",
                                                    "description": "カタログバージョン"
                                                }
                                            },
                                            "description": "アクターカタログコードオブジェクト"
                                        },
                                        "wf": {
                                            "type": "object",
                                            "properties": {
                                                "_value": {
                                                    "type": "integer",
                                                    "description": "カタログコード"
                                                },
                                                "_ver": {
                                                    "type": "integer",
                                                    "description": "カタログバージョン"
                                                }
                                            },
                                            "description": "WF定義カタログコードオブジェクト"
                                        },
                                        "app": {
                                            "type": "object",
                                            "properties": {
                                                "_value": {
                                                    "type": "integer",
                                                    "description": "カタログコード"
                                                },
                                                "_ver": {
                                                    "type": "integer",
                                                    "description": "カタログバージョン"
                                                }
                                            },
                                            "description": "APP定義カタログコードオブジェクト"
                                        },
                                        "expireAt": {
                                            "type": "string",
                                            "description": "有効期限(yyyy-MM-ddTHH:MM:SS.SSS+0900"
                                        }
                                    }
                                },
                                "example": {
                                    "identifyCode": "ukO8z+Xf8vv7yxXQj2Hpo",
                                    "actor": {
                                        "_value": 1000004,
                                        "_ver": 1
                                    },
                                    "app": null,
                                    "wf": {
                                        "_value": 1000007,
                                        "_ver": 1
                                    },
                                    "expireAt": "2020-12-01T00:00:00.000+0900"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/code/verified": {
            "post": {
                "tags": [
                    "確認済本人性確認コード生成"
                ],
                "description": "確認済の本人性確認コードを発行します。",
                "requestBody": {
                    "description": "確認済本人性確認コード生成用のリクエスト",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "description": "確認コード生成情報",
                                "properties": {
                                    "pxrId": {
                                        "type": "string",
                                        "description": "連携PXR-ID"
                                    },
                                    "userId": {
                                        "type": "string",
                                        "description": "連携利用者ID"
                                    },
                                    "actor": {
                                        "type": "object",
                                        "properties": {
                                            "_value": {
                                                "type": "integer",
                                                "description": "連携アクターカタログコード"
                                            },
                                            "_ver": {
                                                "type": "integer",
                                                "description": "連携アクターカタログバージョン"
                                            }
                                        },
                                        "description": "アクターカタログコードオブジェクト"
                                    },
                                    "wf": {
                                        "type": "object",
                                        "properties": {
                                            "_value": {
                                                "type": "integer",
                                                "description": "連携wfカタログコード"
                                            },
                                            "_ver": {
                                                "type": "integer",
                                                "description": "連携wfカタログバージョン"
                                            }
                                        },
                                        "description": "WF定義カタログコードオブジェクト"
                                    },
                                    "app": {
                                        "type": "object",
                                        "properties": {
                                            "_value": {
                                                "type": "integer",
                                                "description": "連携appカタログコード"
                                            },
                                            "_ver": {
                                                "type": "integer",
                                                "description": "連携appカタログバージョン"
                                            }
                                        },
                                        "description": "APP定義カタログコードオブジェクト"
                                    }
                                },
                                "example": {
                                    "pxrId": "test.org",
                                    "userId": "test.bank",
                                    "actor": {
                                        "_value": 1000004,
                                        "_ver": 1
                                    },
                                    "app": null,
                                    "wf": {
                                        "_value": 1000007,
                                        "_ver": 1
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "確認済本人性確認コード生成に成功した際のレスポンス",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "description": "確認コード生成情報",
                                    "properties": {
                                        "identifyCode": {
                                            "type": "string",
                                            "description": "本人性確認コード"
                                        },
                                        "pxrId": {
                                            "type": "string",
                                            "description": "連携PXR-ID"
                                        },
                                        "userId": {
                                            "type": "string",
                                            "description": "連携利用者ID"
                                        },
                                        "actor": {
                                            "type": "object",
                                            "properties": {
                                                "_value": {
                                                    "type": "integer",
                                                    "description": "連携アクターカタログコード"
                                                },
                                                "_ver": {
                                                    "type": "integer",
                                                    "description": "連携アクターカタログバージョン"
                                                }
                                            },
                                            "description": "アクターカタログコードオブジェクト"
                                        },
                                        "wf": {
                                            "type": "object",
                                            "properties": {
                                                "_value": {
                                                    "type": "integer",
                                                    "description": "連携wfカタログコード"
                                                },
                                                "_ver": {
                                                    "type": "integer",
                                                    "description": "連携wfカタログバージョン"
                                                }
                                            },
                                            "description": "WF定義カタログコードオブジェクト"
                                        },
                                        "app": {
                                            "type": "object",
                                            "properties": {
                                                "_value": {
                                                    "type": "integer",
                                                    "description": "連携appカタログコード"
                                                },
                                                "_ver": {
                                                    "type": "integer",
                                                    "description": "連携appカタログバージョン"
                                                }
                                            },
                                            "description": "APP定義カタログコードオブジェクト"
                                        },
                                        "expireAt": {
                                            "type": "string",
                                            "description": "有効期限(yyyy-MM-ddTHH:MM:SS.SSS+0900"
                                        }
                                    }
                                },
                                "example": {
                                    "identifyCode": "ukO8z+Xf8vv7yxXQj2Hpo",
                                    "pxrId": "test.org",
                                    "userId": "test.bank",
                                    "actor": {
                                        "_value": 1000004,
                                        "_ver": 1
                                    },
                                    "app": null,
                                    "wf": {
                                        "_value": 1000007,
                                        "_ver": 1
                                    },
                                    "expireAt": "2020-12-01T00:00:00.000+0900"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/url": {
            "post": {
                "tags": [
                    "URL発行"
                ],
                "description": "本人性確認を閲覧する為のURLを発行します。",
                "requestBody": {
                    "description": "発行するURL情報",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "description": "発行するURLに関するリクエスト",
                                "properties": {
                                    "identifyCode": {
                                        "type": "string",
                                        "description": "本人性確認コード"
                                    },
                                    "urlType": {
                                        "type": "number",
                                        "required": [
                                            "0",
                                            "1"
                                        ],
                                        "description": "発行URL種別(0: 本人用, 1: 第三者用)"
                                    },
                                    "userId": {
                                        "type": "string",
                                        "description": "ユーザーID"
                                    }
                                },
                                "example": {
                                    "identifyCode": "ukO8z+Xf8vv7yxXQj2Hpo",
                                    "urlType": 1,
                                    "userId": "123456"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "URLの発行に成功した際のレスポンス",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "description": "発行URL",
                                    "properties": {
                                        "url": {
                                            "type": "string",
                                            "description": "発行URL"
                                        }
                                    },
                                    "example": {
                                        "url": "https://xxxx.xxx/confirm/third-party/{本人性確認コード}/"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/url/issue": {
            "post": {
                "tags": [
                    "URL発行"
                ],
                "description": "本人性確認を閲覧する為のURLを発行します。",
                "requestBody": {
                    "description": "発行するURL情報",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "description": "発行するURLに関するリクエスト",
                                "properties": {
                                    "identifyCode": {
                                        "type": "string",
                                        "description": "本人性確認コード"
                                    },
                                    "urlType": {
                                        "type": "number",
                                        "required": [
                                            "0",
                                            "1"
                                        ],
                                        "description": "発行URL種別(0: 本人用, 1: 第三者用)"
                                    },
                                    "userId": {
                                        "type": "string",
                                        "description": "ユーザーID"
                                    }
                                },
                                "example": {
                                    "urlType": 1,
                                    "userId": "123456"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "URLの発行に成功した際のレスポンス",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "description": "発行URL",
                                    "properties": {
                                        "url": {
                                            "type": "string",
                                            "description": "発行URL"
                                        }
                                    },
                                    "example": {
                                        "url": "https://xxxx.xxx/confirm/third-party/{本人性確認コード}/"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/url/confirm": {
            "post": {
                "tags": [
                    "URL確認"
                ],
                "description": "本人性確認を閲覧する為のURLを発行します。",
                "requestBody": {
                    "description": "発行するURL情報",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "description": "発行するURLに関するリクエスト",
                                "properties": {
                                    "path": {
                                        "type": "string",
                                        "description": "パス"
                                    }
                                },
                                "example": {
                                    "path": "OTY1MDZlYjktYmY5NC00NmQ1LWI1NzQtYTFiZDkxNzQzNzJj"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "URLの発行に成功した際のレスポンス",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "description": "発行URL",
                                    "properties": {
                                        "url": {
                                            "type": "string",
                                            "description": "発行URL"
                                        }
                                    },
                                    "example": {
                                        "url": "https://xxxx.xxx/confirm/third-party/{本人性確認コード}/"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/verify/others/{identifyCode}": {
            "put": {
                "tags": [
                    "第三者による本人性確認"
                ],
                "description": "本人性を第三者によって確認されたとき、データを更新します。",
                "parameters": [
                    {
                        "name": "identifyCode",
                        "description": "本人性確認コード",
                        "in": "path",
                        "schema": {
                            "type": "string"
                        },
                        "required": true
                    }
                ],
                "requestBody": {
                    "description": "確認結果ステータス",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "description": "確認結果を内包したリクエスト",
                                "properties": {
                                    "status": {
                                        "type": "number",
                                        "description": "本人性確認のステータス(1: 成功, 2: 失敗)"
                                    }
                                },
                                "example": {
                                    "status": 1
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "本人性確認に成功したステータスコード",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        },
        "/acquisition/identification/{identifyCode}": {
            "get": {
                "tags": [
                    "本人性確認事項 取得"
                ],
                "description": "本人性確認事項を取得します。",
                "parameters": [
                    {
                        "name": "identifyCode",
                        "description": "本人性確認コード",
                        "in": "path",
                        "schema": {
                            "type": "string"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "パスパラメーターのコードのデータ取得に成功した際のレスポンス",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "description": "照合結果",
                                    "properties": {
                                        "userId": {
                                            "type": "string",
                                            "description": "利用者ID"
                                        },
                                        "actor": {
                                            "type": "object",
                                            "properties": {
                                                "_value": {
                                                    "type": "integer",
                                                    "description": "カタログコード"
                                                },
                                                "_ver": {
                                                    "type": "integer",
                                                    "description": "カタログバージョン"
                                                }
                                            },
                                            "description": "アクターカタログコードオブジェクト"
                                        },
                                        "wf": {
                                            "type": "object",
                                            "properties": {
                                                "_value": {
                                                    "type": "integer",
                                                    "description": "カタログコード"
                                                },
                                                "_ver": {
                                                    "type": "integer",
                                                    "description": "カタログバージョン"
                                                }
                                            },
                                            "description": "WF定義カタログコードオブジェクト"
                                        },
                                        "app": {
                                            "type": "object",
                                            "properties": {
                                                "_value": {
                                                    "type": "integer",
                                                    "description": "カタログコード"
                                                },
                                                "_ver": {
                                                    "type": "integer",
                                                    "description": "カタログバージョン"
                                                }
                                            },
                                            "description": "APP定義カタログコードオブジェクト"
                                        },
                                        "identification": {
                                            "type": "array",
                                            "description": "本人性確認事項",
                                            "items": {
                                                "$ref": "#/components/schemas/identification"
                                            }
                                        }
                                    }
                                },
                                "example": {
                                    "userId": "123456",
                                    "actor": {
                                        "_value": 1000003,
                                        "_ver": 1
                                    },
                                    "wf": {
                                        "_value": 1000004,
                                        "_ver": 1
                                    },
                                    "identification": [
                                        {
                                            "template": {
                                                "_code": {
                                                    "_value": "30001",
                                                    "_ver": 1
                                                },
                                                "item-group": [
                                                    {
                                                        "title": "氏名",
                                                        "item": [
                                                            {
                                                                "title": "姓",
                                                                "type": {
                                                                    "_value": 30019,
                                                                    "_ver": 1
                                                                },
                                                                "content": "サンプル"
                                                            },
                                                            {
                                                                "title": "名",
                                                                "type": {
                                                                    "_value": 30020,
                                                                    "_ver": 1
                                                                },
                                                                "content": "太郎"
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        "title": "性別",
                                                        "item": [
                                                            {
                                                                "title": "性別",
                                                                "type": {
                                                                    "_value": 30021,
                                                                    "_ver": 1
                                                                },
                                                                "content": "男"
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        "title": "生年月日",
                                                        "item": [
                                                            {
                                                                "title": "生年月日",
                                                                "type": {
                                                                    "_value": 30022,
                                                                    "_ver": 1
                                                                },
                                                                "content": "2000-01-01"
                                                            }
                                                        ]
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        },
        "/collate": {
            "post": {
                "tags": [
                    "本人性確認コード照合"
                ],
                "description": "本人性確認コード照合を行い、照合結果を取得します。",
                "requestBody": {
                    "description": "照合結果",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "description": "照合する本人性確認コード",
                                "properties": {
                                    "identifyCode": {
                                        "type": "string",
                                        "description": "本人性確認コード"
                                    }
                                },
                                "example": {
                                    "identifyCode": "ukO8z+Xf8vv7yxXQj2Hpo"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "照合に成功した際のレスポンス",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "description": "照合結果",
                                    "properties": {
                                        "pxrId": {
                                            "type": "string",
                                            "description": "PXR-ID"
                                        },
                                        "userId": {
                                            "type": "string",
                                            "description": "利用者ID"
                                        },
                                        "actor": {
                                            "type": "object",
                                            "properties": {
                                                "_value": {
                                                    "type": "integer",
                                                    "description": "カタログコード"
                                                },
                                                "_ver": {
                                                    "type": "integer",
                                                    "description": "カタログバージョン"
                                                }
                                            },
                                            "description": "アクターカタログコードオブジェクト"
                                        },
                                        "wf": {
                                            "type": "object",
                                            "properties": {
                                                "_value": {
                                                    "type": "integer",
                                                    "description": "カタログコード"
                                                },
                                                "_ver": {
                                                    "type": "integer",
                                                    "description": "カタログバージョン"
                                                }
                                            },
                                            "description": "WF定義カタログコードオブジェクト"
                                        },
                                        "app": {
                                            "type": "object",
                                            "properties": {
                                                "_value": {
                                                    "type": "integer",
                                                    "description": "カタログコード"
                                                },
                                                "_ver": {
                                                    "type": "integer",
                                                    "description": "カタログバージョン"
                                                }
                                            },
                                            "description": "APP定義カタログコードオブジェクト"
                                        }
                                    },
                                    "example": {
                                        "pxrId": "sample.pxrid",
                                        "userId": "123456",
                                        "actor": {
                                            "_value": 1000003,
                                            "_ver": 1
                                        },
                                        "wf": {
                                            "_value": 1000004,
                                            "_ver": 1
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/ind/collate": {
            "post": {
                "tags": [
                    "個人による本人性確認コード照合"
                ],
                "description": "本人性確認コード照合を行い、照合結果を取得します。",
                "requestBody": {
                    "description": "照合結果",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "description": "照合する本人性確認コード",
                                "properties": {
                                    "identifyCode": {
                                        "type": "string",
                                        "description": "本人性確認コード"
                                    }
                                },
                                "example": {
                                    "identifyCode": "ukO8z+Xf8vv7yxXQj2Hpo"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "照合に成功した際のレスポンス",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "description": "照合結果",
                                    "properties": {
                                        "pxrId": {
                                            "type": "string",
                                            "description": "PXR-ID"
                                        },
                                        "userId": {
                                            "type": "string",
                                            "description": "利用者ID"
                                        },
                                        "actor": {
                                            "type": "object",
                                            "properties": {
                                                "_value": {
                                                    "type": "integer",
                                                    "description": "カタログコード"
                                                },
                                                "_ver": {
                                                    "type": "integer",
                                                    "description": "カタログバージョン"
                                                }
                                            },
                                            "description": "アクターカタログコードオブジェクト"
                                        },
                                        "wf": {
                                            "type": "object",
                                            "properties": {
                                                "_value": {
                                                    "type": "integer",
                                                    "description": "カタログコード"
                                                },
                                                "_ver": {
                                                    "type": "integer",
                                                    "description": "カタログバージョン"
                                                }
                                            },
                                            "description": "WF定義カタログコードオブジェクト"
                                        },
                                        "app": {
                                            "type": "object",
                                            "properties": {
                                                "_value": {
                                                    "type": "integer",
                                                    "description": "カタログコード"
                                                },
                                                "_ver": {
                                                    "type": "integer",
                                                    "description": "カタログバージョン"
                                                }
                                            },
                                            "description": "APP定義カタログコードオブジェクト"
                                        }
                                    },
                                    "example": {
                                        "pxrId": "sample.pxrid",
                                        "userId": "123456",
                                        "actor": {
                                            "_value": 1000003,
                                            "_ver": 1
                                        },
                                        "wf": {
                                            "_value": 1000004,
                                            "_ver": 1
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/user/settings": {
            "post": {
                "tags": [
                    "利用者情報設定"
                ],
                "description": "利用者情報を設定します。",
                "requestBody": {
                    "description": "利用者情報",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "description": "利用者情報に関するリクエスト",
                                "properties": {
                                    "identifyCode": {
                                        "type": "string",
                                        "description": "本人性確認コード"
                                    },
                                    "userId": {
                                        "type": "string",
                                        "description": "利用者ID"
                                    }
                                },
                                "example": {
                                    "identifyCode": "ukO8z+Xf8vv7yxXQj2Hpo",
                                    "userId": "123456"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "利用者情報設定に成功した際のレスポンス",
                        "content": {
                            "application/json": {}
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "identification": {
                "oneOf": [
                    {
                        "$ref": "#/components/schemas/template"
                    }
                ]
            },
            "template": {
                "type": "object",
                "properties": {
                    "_code": {
                        "type": "object",
                        "properties": {
                            "_value": {
                                "type": "integer",
                                "description": "カタログコード"
                            },
                            "_ver": {
                                "type": "integer",
                                "description": "カタログバージョン"
                            }
                        }
                    },
                    "item-group": {
                        "type": "array",
                        "description": "項目グループ",
                        "items": {
                            "$ref": "#/components/schemas/item-group"
                        }
                    }
                }
            },
            "item-group": {
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string",
                        "description": "項目名"
                    },
                    "item": {
                        "type": "array",
                        "description": "項目",
                        "items": {
                            "$ref": "#/components/schemas/item"
                        }
                    }
                }
            },
            "item": {
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string",
                        "description": "項目名"
                    },
                    "type": {
                        "type": "object",
                        "properties": {
                            "_value": {
                                "type": "integer",
                                "description": "カタログコード"
                            },
                            "_ver": {
                                "type": "integer",
                                "description": "カタログバージョン"
                            }
                        }
                    },
                    "content": {
                        "type": "string",
                        "description": "内容"
                    }
                }
            }
        }
    }
}